@startuml
class com.passwordmanager.UserInteraction {
- Terminal terminal
- Scanner scanner
- PasswordGenerator passwordGenerator
- UserCredentialsService userCredentialsService
- Cryptography cryptography
- VaultMetaDataService vaultMetaDataService
- UserCredentials userCredentials
+ boolean startMenu()
- boolean inputCredentials()
+ void menu()
- void executeMainMenuChoice(int)
+ void setMasterPass()
- void showPassword()
- void addDetailsMenu()
- byte[] inputPasswordMenu()
- byte[] genPasswordMenu()
- String inputEmail()
- {static} boolean validateEmail(String)
- String inputWebsite()
- int choose()
- void displayPassword(char[])
}


class com.passwordmanager.UserInteraction$SecurityTerminationException {
}
class com.passwordmanager.Style {
+ {static} String RESET
+ {static} String RED
+ {static} String GREEN
+ {static} String YELLOW
+ {static} String BLUE
+ {static} String MAGENTA
+ {static} String CYAN
+ {static} String BOLD
+ {static} String BOLD_RED
+ {static} String BOLD_GREEN
+ {static} String BOLD_YELLOW
+ {static} String BOLD_BLUE
+ {static} String BOLD_MAGENTA
+ {static} String BOLD_CYAN
+ {static} String RING
}

class com.passwordmanager.DataBlock {
- byte[] data
- byte[] iv
+ byte[] getData()
+ byte[] getIv()
}


class com.passwordmanager.vaultmetadata.VaultMetaDataDAO {
+ void saveUserCredentials(Connection,VaultMetaData)
+ VaultMetaData getUserCredentials(Connection,UUID)
+ UserLoginInfo getLoginInfo(Connection,UUID)
+ void updateLoginInfo(Connection,UserLoginInfo)
+ void updateLoginAttempts(Connection,UserLoginInfo)
+ int noOfUsers(Connection,String)
+ UUID retrieveUUID(Connection,String)
}

enum com.passwordmanager.LogInStatus {
+  WRONG_PASSWORD
+  ACCOUNT_LOCKED
+  NO_USER
+  USER_VERIFIED
+  USER_EXIST
+  UNKNOWN
}

class com.passwordmanager.usercredentials.UserCredentialsService {
- Scanner scanner
- VaultMetaDataService vaultMetaDataService
- UserCredentialsDAO userCredentialsDAO
- Connection getConnection()
+ void saveUserCredentials(UserCredentials)
+ LogInStatus deleteSavedCredentials()
}


class com.passwordmanager.usercredentials.UserCredentials {
- UUID userID
- String username
- String email
- byte[] password
- String tag
- String keyword
- String website
- DataBlock dataBlock
- Cryptography cryptography
+ void setUserID(UUID)
+ void setUsername(String)
+ void setEmail(String)
+ void setPassword(byte[])
+ void setTag(String)
+ void setKeyword(String)
+ void setWebsite(String)
+ UUID getUserID()
+ String getUsername()
+ String getEmail()
+ String getTag()
+ String getKeyword()
+ String getWebsite()
+ DataBlock getEncryptedInfo()
}


class com.passwordmanager.PasswordGenerator {
- SecureRandom secureRandom
- Scanner scanner
- char[] genPassword(int)
+ char[] genPassword()
- char[] genStrongPassword(int)
- boolean checkPassword(char[])
- boolean checkUppercase(char[])
- boolean checkLowercase(char[])
- boolean checkDigit(char[])
- boolean checkSpecialChar(char[])
}


class com.passwordmanager.vaultmetadata.VaultMetaData {
- String username
- byte[] verificationSecretKey
- byte[] verificationSalt
- byte[] encryptionSalt
- byte[] encryptedDataKey
- byte[] dataKeyIV
+ String getUsername()
+ byte[] getVerificationSalt()
+ byte[] getVerificationSecretKey()
+ byte[] getEncryptionSalt()
+ byte[] getEncryptedDataKey()
+ byte[] getDataKeyIV()
}


class com.passwordmanager.vaultmetadata.VaultMetaDataService {
- Scanner scanner
- Terminal terminal
- Cryptography cryptography
- UserCredentials userCredentials
- VaultMetaDataDAO vaultMetaDataDAO
+ Connection getTransactionConnection()
+ LogInStatus verifyLoginCredentials(String,byte[])
- LogInStatus startTransaction(Connection,UUID,byte[])
- void lockedAccount(Connection,int)
- LogInStatus verifyPassword(Connection,UUID,byte[])
- LogInStatus updateBruteForceProtection(Connection,UUID,int)
+ void saveVaultMetaData(VaultMetaData)
+ LogInStatus checkUsername(Connection,String)
+ UUID getUserID(Connection,String)
}


class com.passwordmanager.Main {
+ {static} void main(String[])
}

class com.passwordmanager.Terminal {
- {static} Console terminal
- {static} boolean isTerminal
+ {static} boolean isTerminal()
+ byte[] readPasswordBytes()
+ byte[] toBytes(char[])
}


class com.passwordmanager.Cryptography {
- SecureRandom secureRandom
- VaultMetaDataService vaultMetaDataService
- byte[] genSalt()
+ byte[] genSecretKey(byte[],byte[])
+ VaultMetaData vaultParam(String,byte[])
+ boolean verifyMasterPassword(byte[],byte[],byte[])
+ void decryptDataKey(byte[],VaultMetaData)
+ DataBlock startEncryption(byte[])
+ byte[] startDecryption(DataBlock)
- byte[] genDataKey()
- SecretKey toSecretKey(byte[])
- byte[] genIV()
+ String genInfo()
- Argon2Parameters.Builder getArgon2Builder(byte[])
- byte[] encryptData(byte[],byte[],byte[])
- byte[] decryptData(byte[],byte[],byte[])
}


class com.passwordmanager.Cryptography$DataKey {
- {static} byte[] dataKey
+ {static} void setDataKey(byte[])
+ {static} byte[] getDataKey()
}


class com.passwordmanager.usercredentials.UserCredentialsDAO {
+ boolean insertUserCredentials(Connection,UserCredentials)
+ void eraseUserCredentials(Connection,UUID)
}

class com.passwordmanager.UserLoginInfo {
- int loginAttempts
- Timestamp currentTime
- UUID userID
- Timestamp lockedUntil
- String interval
+ UUID getUserID()
+ int getLoginAttempts()
+ Timestamp getLockedUntil()
+ Timestamp getCurrentTime()
+ String getInterval()
}




com.passwordmanager.UserInteraction +.. com.passwordmanager.UserInteraction$SecurityTerminationException
com.passwordmanager.RuntimeException <|-- com.passwordmanager.UserInteraction$SecurityTerminationException
com.passwordmanager.Cryptography +.. com.passwordmanager.Cryptography$DataKey
@enduml